---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tzcronjobs.cronjobber.hidde.co
spec:
  group: cronjobber.hidde.co
  names:
    plural: tzcronjobs
    singular: tzcronjob
    kind: TZCronJob
    listKind: TZCronJobList
    shortNames:
      - tzc
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - name: Schedule
      type: string
      description: The schedule defining the interval a TZCronJob is run
      jsonPath: .spec.schedule
    - name: Time zone
      type: string
      description: The time zone the interval of a TZCronJob is calculated in
      jsonPath: .spec.timezone
    - name: Last schedule
      type: date
      description: The last time a Job was scheduled by a TZCronJob
      jsonPath: .status.lastScheduleTime
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp    
    name: v1alpha1
    served: true
    storage: true      
    subresources:
      status: {}
