---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - cronjobber.hidde.co
  resources:
  - tzcronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cronjobber.hidde.co
  resources:
  - tzcronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - cronjobber.hidde.co
  resources:
  - tzcronjobs/status
  verbs:
  - get
  - patch
  - update
