# permissions for end users to view tzcronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tzcronjob-viewer-role
rules:
- apiGroups:
  - cronjobber.hidde.co
  resources:
  - tzcronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cronjobber.hidde.co
  resources:
  - tzcronjobs/status
  verbs:
  - get
