/*
Copyright 2019 The Cronjobber Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/hiddeco/cronjobber/pkg/apis/cronjobber/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTZCronJobs implements TZCronJobInterface
type FakeTZCronJobs struct {
	Fake *FakeCronjobberV1alpha1
	ns   string
}

var tzcronjobsResource = schema.GroupVersionResource{Group: "cronjobber.hidde.co", Version: "v1alpha1", Resource: "tzcronjobs"}

var tzcronjobsKind = schema.GroupVersionKind{Group: "cronjobber.hidde.co", Version: "v1alpha1", Kind: "TZCronJob"}

// Get takes name of the tZCronJob, and returns the corresponding tZCronJob object, and an error if there is any.
func (c *FakeTZCronJobs) Get(name string, options v1.GetOptions) (result *v1alpha1.TZCronJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(tzcronjobsResource, c.ns, name), &v1alpha1.TZCronJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TZCronJob), err
}

// List takes label and field selectors, and returns the list of TZCronJobs that match those selectors.
func (c *FakeTZCronJobs) List(opts v1.ListOptions) (result *v1alpha1.TZCronJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(tzcronjobsResource, tzcronjobsKind, c.ns, opts), &v1alpha1.TZCronJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TZCronJobList{ListMeta: obj.(*v1alpha1.TZCronJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.TZCronJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tZCronJobs.
func (c *FakeTZCronJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(tzcronjobsResource, c.ns, opts))

}

// Create takes the representation of a tZCronJob and creates it.  Returns the server's representation of the tZCronJob, and an error, if there is any.
func (c *FakeTZCronJobs) Create(tZCronJob *v1alpha1.TZCronJob) (result *v1alpha1.TZCronJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(tzcronjobsResource, c.ns, tZCronJob), &v1alpha1.TZCronJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TZCronJob), err
}

// Update takes the representation of a tZCronJob and updates it. Returns the server's representation of the tZCronJob, and an error, if there is any.
func (c *FakeTZCronJobs) Update(tZCronJob *v1alpha1.TZCronJob) (result *v1alpha1.TZCronJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(tzcronjobsResource, c.ns, tZCronJob), &v1alpha1.TZCronJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TZCronJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTZCronJobs) UpdateStatus(tZCronJob *v1alpha1.TZCronJob) (*v1alpha1.TZCronJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(tzcronjobsResource, "status", c.ns, tZCronJob), &v1alpha1.TZCronJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TZCronJob), err
}

// Delete takes name of the tZCronJob and deletes it. Returns an error if one occurs.
func (c *FakeTZCronJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(tzcronjobsResource, c.ns, name), &v1alpha1.TZCronJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTZCronJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(tzcronjobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TZCronJobList{})
	return err
}

// Patch applies the patch and returns the patched tZCronJob.
func (c *FakeTZCronJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TZCronJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(tzcronjobsResource, c.ns, name, pt, data, subresources...), &v1alpha1.TZCronJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TZCronJob), err
}
