---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
rules:
  - apiGroups: ['cronjobber.hidde.co']
    resources: ['*']
    verbs: ['*']
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['*']
  - apiGroups: ['']
    resources: ['events']
    verbs: ['create', 'patch', 'update']
